export const Token ={
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHN1bnNoaW5lLmNvbSIsIlVzZXJJZCI6IjJhNzJlNDA2LTE1YTktNGJiNS05ODNiLWE0NGNiMGJkNzMyMyIsIlVzZXJOYW1lIjoic3Vuc2hpbmUtMDEiLCJqdGkiOiIyZGY4ZjRjYi0wYmQxLTQ0YjktYjRjOS1mYzcwMDg1ZjZlNjciLCJuYmYiOjE2ODk1NjcxMzcsImV4cCI6MTY4OTYxMDMzNywiaXNzIjoic2h1dmEuY29tIiwiYXVkIjoic2h1dmEuY29tIn0.YqJKeB2UKwIemfRJUebbz-XDvbtMxprqWR60rsUtV-g"
}
export default Token
     